### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN error within the browser when the repo name/owner contains dots

### ISSUE THREAD

**Issue by Adito5393** [woodpecker-ci/plugin-surge-preview#1]
Thanks a lot for this simple & awesome plugin! I've tried it with Gitea & Drone setup. (I will probably switch to woodpecker when cron PR https://github.com/woodpecker-ci/woodpecker/pull/934 is merged)

I currently get this SSL error due to my repo containing dots in the name:

```log
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for REPO_OWNER-docs.app.com-pr-21.surge.sh. The certificate is only valid for the following names: *.surge.sh, surge.sh
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

Would you accept a PR to handle my use case and replace dots in the name with `-` to pass this URL to `surge`?

I have 0 experience with building go apps, but I can give it a try & see how far I get if you are too busy to fix it.

**Comment by anbraten** [comment]
That should be quite easy to fix. The corresponding line would be: https://github.com/woodpecker-ci/plugin-surge-preview/blob/3ef567c0a3e47651c56f1e38433cf7902274503d/plugin.go#L120

Some code like the following should do the trick:

```go
pattern := regexp.MustCompile(`[^a-z0-9\-]`)
owner := pattern.ReplaceAllString(p.RepoOwner, "-")
```

Looking forward to your PR.
