### ISSUE TITLE
Deleting never works (PR closed)

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/plugin-surge-preview#49]
See e.g. https://ci.woodpecker-ci.org/repos/3780/pipeline/12163/3
Error:
```
Surge.sh preview plugin
not Found
```

**Comment by 6543** [comment]
well it do look like it works now https://ci.woodpecker-ci.org/repos/3780/pipeline/13573/3 ... kind a

the initial issue should be fixed with https://github.com/woodpecker-ci/woodpecker/pull/3442

**Comment by 6543** [comment]
so I'll close this one ;)

and open a new one for the next one
